version: '3.8'

services:
  flaskapp:
    image: python:3.9
    volumes:
      - ./app:/app
    working_dir: /app
    command: /bin/sh -c "pip install --upgrade pip && pip install -r requirements.txt && python app.py"
    ports:
      - "5000:5000"
    environment:
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - GEOCODE_API_KEY=${GEOCODE_API_KEY}

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - flaskapp
