name: CI for stormsentry-nginx (dev)

on:
  push:
    branches:
      - stephen-edits
    paths:
      - 'Backend/nginx/**'

jobs:

  build-test-nginx:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t stormsentry-nginx .
        working-directory: ./Backend/nginx

      - name: Run Docker container
        run: |
          docker run -d --name nginx-test -p 8080:80 stormsentry-nginx
          #wait for health check to verify service is booted before continuing to tests
          until [ "$(docker inspect --format='{{.State.Health.Status}}' nginx-test)" == "healthy" ]; do
              sleep 1;
              echo "Waiting for Nginx to be ready...";
          done


      - name: Test Nginx responses
        run: |
          response=$(curl -o /dev/null -s -w "%{http_code}\n" http://localhost:8080)
          if [ "$response" -ne 200 ]; then
            echo "Nginx did not return a 200 OK on the root path"
            exit 1
          fi
          response=$(curl -o /dev/null -s -w "%{http_code}\n" -H "Content-Type: text/plain" http://localhost:8080/api/weather)
          if [ "$response" -ne 415 ]; then
            echo "Nginx did not return a 415 Unsupported Media Type for /api/weather without JSON"
            exit 1
          fi

      - name: Clean up
        run: docker rm -f nginx-test
